- color: fef2c0
  description: Author 可申请锁住当前讨论
  name: Locked
- color: 45AB16
  description: ""
  name: UX
- color: 0A7151
  description: ""
  name: 作品集
- color: 00058E
  description: ""
  name: 字体
- color: 3A2F9D
  description: ""
  name: 平面设计
- color: E8EDD2
  description: ""
  name: 建筑
- color: 1C60D0
  description: ""
  name: 设计师
